#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-google-http-java-client
Version  : 1.23.0
Release  : 3
URL      : https://github.com/googleapis/google-http-java-client/archive/1.23.0.tar.gz
Source0  : https://github.com/googleapis/google-http-java-client/archive/1.23.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar
Source2  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.pom
Source3  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar
Source4  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.pom
Source5  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.22.0/google-http-client-parent-1.22.0.pom
Source6  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.23.0/google-http-client-parent-1.23.0.pom
Source7  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar
Source8  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.pom
Source9  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar
Source10  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause xpp
Requires: mvn-google-http-java-client-data = %{version}-%{release}
Requires: mvn-google-http-java-client-license = %{version}-%{release}

%description
# Google HTTP Client Library for Java
## Description
Written by Google, the Google HTTP Client Library for Java is a flexible, efficient, and powerful Java library for accessing any resource on the web via HTTP. The library has the following features:
- Pluggable HTTP transport abstraction that allows you to use any low-level library such as java.net.HttpURLConnection, Apache HTTP Client, or URL Fetch on Google App Engine.
- Efficient JSON and XML data models for parsing and serialization of HTTP response and request content.  The JSON and XML libraries are also fully pluggable, and they include support for [Jackson](https://github.com/FasterXML/jackson) and Android's GSON libraries for JSON.

%package data
Summary: data components for the mvn-google-http-java-client package.
Group: Data

%description data
data components for the mvn-google-http-java-client package.


%package license
Summary: license components for the mvn-google-http-java-client package.
Group: Default

%description license
license components for the mvn-google-http-java-client package.


%prep
%setup -q -n google-http-java-client-1.23.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client/LICENSE
cp google-http-client-assembly/LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_LICENSE.txt
cp google-http-client-assembly/dependencies/APACHE-LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_APACHE-LICENSE.txt
cp google-http-client-assembly/dependencies/BSD-LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_BSD-LICENSE.txt
cp google-http-client-assembly/dependencies/xpp3_LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_xpp3_LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.22.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.22.0/google-http-client-parent-1.22.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0/google-http-client-parent-1.23.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.22.0/google-http-client-parent-1.22.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0/google-http-client-parent-1.23.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-google-http-java-client/LICENSE
/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_LICENSE.txt
/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_APACHE-LICENSE.txt
/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_BSD-LICENSE.txt
/usr/share/package-licenses/mvn-google-http-java-client/google-http-client-assembly_dependencies_xpp3_LICENSE.txt
