#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-google-http-java-client
Version  : 1.23.0
Release  : 1
URL      : https://github.com/googleapis/google-http-java-client/archive/1.23.0.tar.gz
Source0  : https://github.com/googleapis/google-http-java-client/archive/1.23.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar
Source2  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.pom
Source3  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client-parent/1.23.0/google-http-client-parent-1.23.0.pom
Source4  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar
Source5  : https://repo1.maven.org/maven2/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-google-http-java-client-data = %{version}-%{release}

%description
# Google HTTP Client Library for Java
## Description
Written by Google, the Google HTTP Client Library for Java is a flexible, efficient, and powerful Java library for accessing any resource on the web via HTTP. The library has the following features:
- Pluggable HTTP transport abstraction that allows you to use any low-level library such as java.net.HttpURLConnection, Apache HTTP Client, or URL Fetch on Google App Engine.
- Efficient JSON and XML data models for parsing and serialization of HTTP response and request content.  The JSON and XML libraries are also fully pluggable, and they include support for [Jackson](https://github.com/FasterXML/jackson) and Android's GSON libraries for JSON.

%package data
Summary: data components for the mvn-google-http-java-client package.
Group: Data

%description data
data components for the mvn-google-http-java-client package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-jackson2/1.23.0/google-http-client-jackson2-1.23.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client-parent/1.23.0/google-http-client-parent-1.23.0.pom
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar
/usr/share/java/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.pom
